name: Docker Image CI

on:
  push:
    branches: [ python2.7 ]
  pull_request:
    branches: [ python2.7 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag domain_analyzer:python2.7-$(date +%s)
